services:
  fuseki:
    image: ghcr.io/kurrawong/fuseki:5.2.0-1
    ports:
      - 3030:3030
    volumes:
      - ./data:/fuseki
    environment:
      - JAVA_OPTIONS=-Xmx2048m -Xms2048m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/$/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
  prez:
    image: "ghcr.io/rdflib/prez:4.22.1"
    ports:
      - "8000:8000"
    environment:
      APP_ROOT_PATH: /prez-backend
      PROXY_HEADERS: true
      FORWARDED_ALLOW_IPS: '*'
      SPARQL_ENDPOINT: 'http://fuseki:3030/fuseki-ogc/query'
      PREZ_TITLE: OGC Rainbow
      PREZ_DESC: OGC Rainbow
      #SYSTEM_URI: https://defs.opengis.net/prez-backend/
      #PREZ_UI_URL: https://defs.opengis.net/prez/
      ENABLE_SPARQL_ENDPOINT: true
      CUSTOM_ENDPOINTS: true
      # ENDPOINT_STRUCTURE: '["catalogs", "col", "it1", "it2", "it3", "it4", "it5"]'
